force-app/main/default/objects/crop__c/crop__c.object-meta.xml
<CustomObject>
    <label>Crop</label>
    <nameField>
        <label>crop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/crop__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vegetables</fullName>
            </value>
            <value>
                <fullName>Fruits</fullName>
            </value>
            <value>
                <fullName>Grains</fullName>
            </value>
            <value>
                <fullName>Leafy</fullName>
            </value>
            <value>
                <fullName>Pulses</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CropService.cls
public with sharing class CropService {

    // Get All Crops
    public static List<Crop__c> getAllCrops() {

        return [
            SELECT Id,
                   Name,
                   Quantity__c,
                   Category__c,
                   Description__c
            FROM Crop__c
        ];
    }

    // Get Single Crop
    public static Crop__c getCropById(Id cropId) {

        return [
            SELECT Id,
                   Name,
                   Quantity__c,
                   Category__c,
                   Description__c
            FROM Crop__c
            WHERE Id = :cropId
            LIMIT 1
        ];
    }

    // Search Crops
    public static List<Crop__c> searchCrops(String searchKey) {

        return [
            SELECT Id,
                   Name,
                   Quantity__c,
                   Category__c,
                   Description__c
            FROM Crop__c
            WHERE Name LIKE :('%' + searchKey + '%')
        ];
    }

    // Filter By Category
    public static List<Crop__c> getCropsByCategory(String category) {

        return [
            SELECT Id,
                   Name,
                   Quantity__c,
                   Category__c,
                   Description__c
            FROM Crop__c
            WHERE Category__c = :category
        ];
    }

    // Create Crop
    public static Crop__c createCrop(Crop__c cropRecord) {

        insert cropRecord;
        return cropRecord;
    }

    // Update Crop
    public static Crop__c updateCrop(Crop__c cropRecord) {

        update cropRecord;
        return cropRecord;
    }

    // Delete Crop
    public static void deleteCrop(Id cropId) {

        Crop__c cropRecord = [
            SELECT Id
            FROM Crop__c
            WHERE Id = :cropId
            LIMIT 1
        ];

        delete cropRecord;
    }
}